app:
    resource: "@AppBundle/Controller/"
    type:     annotation

user_registration:
  path: /user/new
  defaults: {_controller: AppBundle:User:new}

fos_js_routing:
      resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"