<?php

namespace AppBundle\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends EntityRepository
{


    public function findRelatedBlogs($blog_Id)
    {

        $qbCat = $this->_em->createQueryBuilder();
        $qbCat->select('ca.id')
            ->from('AppBundle:Blog', 'bl')
            ->join('bl.categories', 'ca')
            ->where('bl.id =:blogid')
            ->setParameter('blogid', $blog_Id);

        $qb = $this->_em->createQueryBuilder();
        $qb->select('b')
            ->from('AppBundle:Blog', 'b')
            ->join('b.categories', 'c')
            ->where($qb->expr()->in('c.id', $qbCat->getDQL()))
            ->andWhere('b.id !=:blogid')
            ->setMaxResults(3)
            ->setParameter('blogid', $blog_Id);
        return $qb->getQuery()->getResult();


    }

    public function getBlogsCategory($categoryId)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('b')
            ->from('AppBundle:Blog', 'b')
            ->join('b.categories', 'c')
            ->where('c.id =:catid')
            ->setParameter('catid', $categoryId);
        return $qb->getQuery()->getResult();
    }


}
