<?php

namespace AppBundle\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends EntityRepository
{


    public function findRelatedBlogs()
    {

        $qbCat = $this->_em->createQueryBuilder();
        $qbCat->select('ca.id')
            ->from('AppBundle:Blog', 'bl')
            ->join('bl.categories', 'ca')
            ->where('bl.id = 37');

        $qb = $this->_em->createQueryBuilder();
        $qb->select('b.id', 'b.title')
            ->from('AppBundle:Blog', 'b')
            ->join('b.categories', 'c')
            ->where($qb->expr()->in('c.id', $qbCat->getDQL()))
            ->andWhere('b.id != 37');
        return $qb->getQuery()->getResult();


    }

    public function getBlogsCategory($categoryId)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('b')
            ->from('AppBundle:Blog', 'b')
            ->join('b.categories', 'c')
            ->where('c.id =:catid')
            ->setParameter('catid', $categoryId);
        return $qb->getQuery()->getResult();
    }


}
