<?php

namespace AppBundle\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * userlikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class userlikeRepository extends EntityRepository
{
    public function findUserLike($blog_Id, $userId)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('ul')
            ->from('AppBundle:User_like', 'ul')
            ->join('ul.blog', 'b')
            ->join('ul.user', 'u')
            ->where('b.id =:blogid')
            ->andWhere('u.id =:userid')
            ->setParameter('blogid', $blog_Id)
            ->setParameter('userid', $userId);
        return $qb->getQuery()->getResult();

    }

    public function countLikesPost($blog_Id)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('ul', 'count(ul.id)')
            ->from('AppBundle:User_like', 'ul')
            ->join('ul.blog', 'b')
            ->where('b.id =:blogid')
            ->setParameter('blogid', $blog_Id);
        return $qb->getQuery()->getResult();

    }

}

